name: CI

on:
  push:
    branches-ignore: [ staging.tmp ]
  pull_request:
    branches-ignore: [ staging.tmp ]

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [
          Android Stable
        ]
        include:
          - os: macos-10.15
            name: Android Stable
            channel: stable
            build_command: rustup target add aarch64-linux-android; cargo clippy --target aarch64-linux-android
            install_deps_command: |
                                  curl -LO https://dl.google.com/android/repository/android-ndk-r21b-linux-x86_64.zip
                                  unzip -qq android-ndk-r21b-linux-x86_64.zip -d $GITHUB_WORKSPACE
                                  export NDK_HOME_BIN="$GITHUB_WORKSPACE/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/bin"
                                  ln -s ${NDK_HOME_BIN}/aarch64-linux-android21-clang ${NDK_HOME_BIN}/aarch64-linux-android-clang
                                  echo "::add-path::$NDK_HOME_BIN"
            make_command: make package
    steps:
    - uses: actions/checkout@v2
    - if: contains(matrix.build_command, 'clippy')
      run: rustup component add clippy
    - name: Install dependencies
      run: ${{ matrix.install_deps_command }}
      shell: bash
    - run: ${{ matrix.build_command }}
      shell: bash
    - run: ${{ matrix.make_command }}
      shell: bash
