name: CI

on:
  push:
    branches-ignore: [ staging.tmp ]
  pull_request:
    branches-ignore: [ staging.tmp ]

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [
          iOS Stable,
          MacOS Stable,
          MacOS Nightly,
          Ubuntu Stable,
          Ubuntu Nightly,
          Windows Stable,
          Windows Nightly,
        ]
        include:
          - os: macos-10.15
            name: iOS Stable
            channel: stable
            build_command: rustup target add aarch64-apple-ios; cargo clippy --target aarch64-apple-ios
          - os: macos-10.15
            name: MacOS Stable
            channel: stable
            build_command: cargo clippy
          - os: macos-10.15
            name: MacOS Nightly
            channel: nightly
            build_command: cargo check
          - os: ubuntu-18.04
            name: Ubuntu Stable
            channel: stable
            build_command: cargo clippy
          - os: ubuntu-18.04
            name: Ubuntu Nightly
            channel: nightly
            build_command: cargo check
          - os: windows-2019
            name: Windows Stable
            channel: stable
            build_command: rustup default stable-msvc; cargo clippy
          - os: windows-2019
            name: Windows Nightly
            channel: nightly
            build_command: rustup default nightly-msvc; cargo clippy
    steps:
    - uses: actions/checkout@v2
    - if: matrix.channel == 'nightly'
      name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - if: contains(matrix.build_command, 'clippy')
      run: rustup component add clippy
    - if: contains(matrix.os, 'ubuntu')
      name: Install glfw3
      run: |
        sudo apt install -f -y cmake
        GLFW_DIR="./libglfw3"
        mkdir $GLFW_DIR
        curl -o $GLFW_DIR/libglfw3-dev_3.3.2-1_amd64.deb http://security.ubuntu.com/ubuntu/pool/universe/g/glfw3/libglfw3-dev_3.3.2-1_amd64.deb
        curl -o $GLFW_DIR/libglfw3_3.3.2-1_amd64.deb http://security.ubuntu.com/ubuntu/pool/universe/g/glfw3/libglfw3_3.3.2-1_amd64.deb
        sudo apt install -f -y $GLFW_DIR/libglfw3_3.3.2-1_amd64.deb
        sudo apt install -f -y $GLFW_DIR/libglfw3-dev_3.3.2-1_amd64.deb
        rm -rf $GLFW_DIR
    - if: contains(matrix.os, 'macos')
      name: Install glfw3
      run: brew install cmake glfw3
    - if: contains(matrix.os, 'windows')
      name: Install glfw3
      run: |
        choco install cmake make
        wget -nc -O https://github.com/glfw/glfw/releases/download/3.3.2/glfw-3.3.2.bin.WIN64.zip &&
        7z x glfw-3.3.2.bin.WIN64.zip -o glfw &&
        cd glfw
        ls -al
    - name: cargo test
      run: cargo test
    - if: contains(matrix.build_command, 'clippy')
      name: cargo clippy
      run: ${{ matrix.build_command }}
    - name: MacOS vulkan-portability
      if: contains(matrix.os, 'macos')
      run: ${{ matrix.build_command }} --features vulkan-portability
    - if: matrix.channel == 'nightly'
      run: cargo +nightly install cbindgen
    - if: matrix.channel == 'nightly'
      run: make VERBOSE=1
    - if: matrix.channel == 'stable'
      run: make package
