name: CI

on:
  push:
    branches-ignore: [ staging.tmp ]
  pull_request:
    branches-ignore: [ staging.tmp ]

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [
          Windows Nightly,
        ]
        include:
          - os: windows-2019
            name: Windows Nightly
            channel: nightly
            build_command: rustup default nightly-msvc; cargo check
            install_deps_command: |
                                  choco install -y --force cmake make
                                  wget -nc -O https://github.com/glfw/glfw/releases/download/3.3.2/glfw-3.3.2.bin.WIN64.zip &&
                                  7z x glfw-3.3.2.bin.WIN64.zip -o glfw &&
                                  cd glfw
                                  ls -al
            make_command: make VERBOSE=1
    steps:
    - uses: actions/checkout@v2
    - if: matrix.channel == 'nightly'
      name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - if: contains(matrix.build_command, 'clippy')
      run: rustup component add clippy
    - name: Install dependencies
      run: ${{ matrix.install_deps_command }}
    - name: cargo test
      run: cargo test
    - if: contains(matrix.build_command, 'clippy')
      name: cargo clippy
      run: ${{ matrix.build_command }}
    - name: MacOS vulkan-portability
      if: contains(matrix.os, 'macos') && !contains(matrix.build_command, 'ios')
      run: ${{ matrix.build_command }} --features vulkan-portability
    - if: matrix.channel == 'nightly'
      run: cargo +nightly install cbindgen
    - run: ${{ matrix.make_command }}
